name: Unzip python

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # Git Checks-out our repository      
    name: reading pyhon script
    steps:      
    - name: Checkout code
      uses: actions/checkout@v4
    - name: setup python and aws cli
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli
        sudo apt-get install python3 python3-pip

    - name: run script
      run: |
        python as_mishra.py
