name: Unzip python

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # Git Checks-out our repository      
    name: reading pyhon script
    steps:      
    - name: Checkout
      uses: actions/checkout@v4
    - name: setup python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.13.0'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: run script
      run: |
        python as_python.py
      
